name: vocabtree
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2
  google_nav_bar: ^5.0.6
  day_night_switcher: ^0.2.0+1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  swipe_cards: ^2.0.0+1
  flutter_tts: ^4.0.2
  simple_circular_progress_bar: ^1.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-ExtraBold.ttf
          weight: 800
