// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHViaaB2CWL14PLQtqqJ5KV0RNyaFhJjI',
    appId: '1:1007747882513:web:11b8bdfa9aac27d4625bb0',
    messagingSenderId: '1007747882513',
    projectId: 'vocabtree-b91f2',
    authDomain: 'vocabtree-b91f2.firebaseapp.com',
    storageBucket: 'vocabtree-b91f2.appspot.com',
    measurementId: 'G-ZFT7S2GVBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwrbsI499YM82he9wSYkJ1_jvvaJO_D4',
    appId: '1:1007747882513:android:4f612636657c99f4625bb0',
    messagingSenderId: '1007747882513',
    projectId: 'vocabtree-b91f2',
    storageBucket: 'vocabtree-b91f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTxxteIfA5o-a8p28GO5vBVPVPdI_Ry5o',
    appId: '1:1007747882513:ios:555e8c4f1b1baa9e625bb0',
    messagingSenderId: '1007747882513',
    projectId: 'vocabtree-b91f2',
    storageBucket: 'vocabtree-b91f2.appspot.com',
    iosBundleId: 'com.example.vocabtree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTxxteIfA5o-a8p28GO5vBVPVPdI_Ry5o',
    appId: '1:1007747882513:ios:555e8c4f1b1baa9e625bb0',
    messagingSenderId: '1007747882513',
    projectId: 'vocabtree-b91f2',
    storageBucket: 'vocabtree-b91f2.appspot.com',
    iosBundleId: 'com.example.vocabtree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHViaaB2CWL14PLQtqqJ5KV0RNyaFhJjI',
    appId: '1:1007747882513:web:61aa5a49a0cd57d7625bb0',
    messagingSenderId: '1007747882513',
    projectId: 'vocabtree-b91f2',
    authDomain: 'vocabtree-b91f2.firebaseapp.com',
    storageBucket: 'vocabtree-b91f2.appspot.com',
    measurementId: 'G-5WRRHBTP7F',
  );
}
